---
- name: PHP | Install Ondrej PHP PPA
  become: true
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: Install PHP 7.1
  apt: pkg={{ item }} state=latest
  become: true
  with_items:
    - php7.1-xml
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-json
    - php7.1-curl
    - php7.1-cli
    - php7.1-common
    - php7.1-mcrypt
    - php7.1-gd
    - php7.1-zip
    - php7.1-fpm

- name: Allow PHP Short Tags
  become: true
  ini_file: dest=/etc/php/7.1/cli/php.ini
    section=PHP
    option=short_open_tag
    value=On
