---
- name: Installs nginx web server
  become: true
  apt: pkg=nginx state=installed update_cache=true

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Update nginx confs
  become: yes
  template: src="vhost.conf" dest="/etc/nginx/sites-available/{{domain}}.conf" owner=www-data group=www-data mode=0644


- name: Enable site
  become: yes
  file: src="/etc/nginx/sites-available/{{domain}}.conf" dest="/etc/nginx/sites-enabled/{{domain}}.conf" owner=www-data group=www-data state=link


- name: Restart Nginx Server
  become: yes
  service: name=nginx state=restarted enabled=yes